import time
import pickle
import numpy as np
from tqdm.auto import tqdm
from playsound import playsound
from brainflow.board_shim import BoardShim, BrainFlowInputParams, BoardIds

from .globals import DELAY as glob_DELAY, SAMPLING_RATE, REQUIRED_PARAMS
from .utils import next_valid


DELAY = glob_DELAY


def set_delay(delay):
    global DELAY
    DELAY = delay
    print(f"Set delay to {DELAY} seconds")


# context manager that starts and ends recording
# returns self, board and data can be retrieved using self.board and self.data
class Recording:
    def __init__(self, serial_port):
        self.serial_port = serial_port
        self.data = None

    def __enter__(self):
        print("Starting recording ...")
        BoardShim.enable_board_logger()
        params = BrainFlowInputParams()
        params.serial_port = self.serial_port
        board = BoardShim(BoardIds.CYTON_BOARD.value, params)

        self.board = board
        self.board.prepare_session()
        self.board.start_stream()

        return self
    
    def __exit__(self, exc_type, exc_value, traceback):
        self.data = self.board.get_board_data()
        self.board.stop_stream()
        self.board.release_session()
        print("Finished recording")


# runs OpenBCI recording and plays audio file during recording
# pads audio file with globals.DELAY seconds
# returns raw data (2d numpy array)
def record(filepath, serial_port):
    recording = Recording(serial_port)
    with recording as rec:
        board = rec.board

        for _ in tqdm(range(DELAY), desc="Padding ..."):
            time.sleep(1)    
            board.insert_marker(1)
        
        print("started audio")
        playsound(filepath)
        print("finished audio")

        board.insert_marker(2)
        for _ in tqdm(range(DELAY), desc="Padding ..."):
            time.sleep(1)

    return recording.data


# takes data (2d np array), channels (dict), and audio_dict (generated by generate_train)
def save_dict(data, channels, audio_dict, check_params=True):
    # Number of samples in the pre-audio delay
    delay_samples = DELAY * SAMPLING_RATE

    soundstats = audio_dict
    audio_sampling_rate = soundstats["sampling_rate"] #10,000 or similar
    soa = soundstats["soa"]/audio_sampling_rate #soa in seconds
    click_count = soundstats["click_count"] #number of clicks
    starts = (SAMPLING_RATE*soundstats["starts"]/audio_sampling_rate) + delay_samples
    ends = (SAMPLING_RATE*soundstats["ends"]/audio_sampling_rate) + delay_samples

    #click count, start loc - convert to indices, end loc, length(seconds)
    results = {
        "data": data,
        "channels": channels,
        "click_idx": starts.astype(int),
        "end_idx": ends.astype(int),
        "soa_seconds": soa,
        "soa_indices": int(soa*SAMPLING_RATE),
        "click_number": click_count,
        "delay": DELAY,
        "audio_dict": audio_dict
    }

    save = True
    if check_params:
        for key in results.keys():
            if key not in REQUIRED_PARAMS:
                print(f"warning: key not in required params: \"{key}\"")
        for key in REQUIRED_PARAMS:
            if key not in results.keys():
                print(f"following key must be in data_dict: \"{key}\"")
                save = False
            
    save_path = next_valid("data", ".pkl")
    if save:
        with open(save_path, 'wb') as f:
            pickle.dump(results, f)
        print(f"saved to {save_path}")
    else:
        print("save aborted")

    return save_path


# opens a .pkl file containing a data dict, then adds kwargs to it if the key is not used
def add_key_val_to_pkl(fp, **kwargs):
    with open(fp, 'rb') as f:
        data = pickle.load(f)
    for key, val in kwargs.items():
        if key in data.keys():
            print(f"\"{key}\" is already in {fp} and has not been added")
            continue
        if key not in REQUIRED_PARAMS:
            print(f"\"{key}\" is not in REQUIRED_PARAMS but has been added")
        else:
            print(f"\"{key}\" has been added")
        data[key] = val
    with open(fp, 'wb') as f:
        pickle.dump(data, f)
